### ISSUE TITLE
No such file called dataset.txt!

### ISSUE THREAD

**Issue by colorblank** [xmlyqing00/AFB-URR#1]
Is this "dataset.txt " created by unify_pretrain_dataset.py or other ".py" file  you didn't release?
PS: glob is built in package in python, no need to state in "requirements.txt".

Now, I'm fine. The "dataset.txt " contains dataset names like this
```
COCO
ECSSD
MSRA10K
PASCAL-S
PASCALVOC2012
```

**Comment by xmlyqing00** [comment]
Oh, I see. I will remove the glob from the requirements.txt  I will explain the dataset.txt in the README.md. Thank you.

**Comment by xmlyqing00** [comment]
I fixed this bug by adding the dataset.txt file in the repository.
