### ISSUE TITLE
Wrong Directory Name

### ISSUE THREAD

**Issue by yoxu515** [xmlyqing00/AFB-URR#11]
2 bugs in unify_pretrain_dataset.py

1, For MSRA10K
line 67-68, the directory name 'MSRA10K_Imgs_GT' is misspelled as 'MARA10K_Imgs_GT'

2, For COCO
line 167, 178, the directory name for the annotations in the downloaded file (2021.12.27) is 'annotations 2' instead of 'annotations'

**Comment by xmlyqing00** [comment]
Hi,

Thanks for pointing it out. I changed the name from "MARA" to "MSRA". For COCO, I downloaded the COCO2017 tran/val annotation zip file, `http://images.cocodataset.org/annotations/annotations_trainval2017.zip`, the annotation directory is still named "annotation". I am not sure what happened to your directory name.

**Comment by yoxu515** [comment]
good, I guess the COCO one is my own problem, the file is renamed by the system to avoid name duplication since another 'annotations' exists.
