### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Cbezz** [xmlyqing00/AFB-URR#13]
Hi,

Ok so, I'm trying to train a custom dataset, either from scratch or from the checkpoint.
When I run:
python train.py --level 0 --dataset dataset_path\ --seed 1 --lr 1e-5 --scheduler-step 3 --new --total-epoch 12 --log --budget 1873920

OR:

python train.py --level 0 --dataset dataset_path\ --seed 1 --lr 1e-5 --scheduler-step 3 --resume checkpoint_path\checkpoint.pth --total-epoch 12 --log --budget 1873920

I get the ValueError mentioned in the title.
I'm guessing this is because it's looking for COCO, ECSSD, MSRA10k, PASCAL-S or PASCALVOC2021 and is only getting my custom dataset, but I would've thought it should still work given the file directories are set out as required.

My dataset_path folder has an Annotations folder, a ImageSets folder and a JPEGImages folder and then inside each of those are folders 0, 1 and 2 with the rest of the files contained in those just like the DAVIS dataset is set out.

What have I done wrong? Really looking forward to using this algorithm :)

**Comment by xmlyqing00** [comment]
Thanks for your interest in my project. Are your question is that you want to train my model with your custom dataset instead of the COCO, MSRA10K, etc. ?

**Comment by Cbezz** [comment]
Yes that's correct, is that possible?
Thanks :)

**Comment by xmlyqing00** [comment]
Yes, it's possible. Just make sure you prepared your dataset in the correct file structure, under the `dataset_path`, you should have
```
  - Annotations/
      - custom1/
      - custom2/
  - JPEGImages/
     - custom1/
     - custom2/
  - dataset.txt
  - mask_palette.png
```
In `dataset.txt`, you should have 2 lines `custom1` and `custom2`.
In my dataset code `./dataset/PreTrain_DS.py` Line 25, you can see that I will read the rows in the variable `dataset_file`, so you have to pass this argument in `train.py` Line 96, 
```
        dataset = PreTrain_DS(args.dataset, output_size=400, clip_n=args.clip_n, max_obj_n=args.obj_n)
```
add argument `dataset_file` when you create the dataset.

**Comment by xmlyqing00** [comment]
Close since long-time inactive.
