### ISSUE TITLE
A difference between your paper and code.

### ISSUE THREAD

**Issue by shoutOutYangJie** [xmlyqing00/AFB-URR#2]
In your paper, you refer to the resolution of backbone output from resnet.layer3, which output stride is 8. But in your code, you don't change original resnet50's stride, leading to a 16 of output stride.

**Comment by shoutOutYangJie** [comment]
By the way,  is the davis benchmark which you mentioned in your paper  davis17 validation or davis17 test-dev ?

**Comment by xmlyqing00** [comment]
> In your paper, you refer to the resolution of backbone output from resnet.layer3, which output stride is 8. But in your code, you don't change original resnet50's stride, leading to a 16 of output stride.

LOL. Interesting quesion. Actually, our code uses the ResNet.layer3 as output. You can see line 47 and line 77 in the AFB-URR.py,
```
        self.res4 = resnet.layer3  # 1/8, 1024
```


> By the way, is the davis benchmark which you mentioned in your paper davis17 validation or davis17 test-dev ?
I use the DAVIS17 train-val dataset for training and evaluation. I didn't test on the test-dev dataset.

**Comment by shoutOutYangJie** [comment]
Hi, I have checked "r4"'s shape. Actually, it is indeed downsampled by 16 stride.






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xmlyqing00/AFB-URR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 中午12:09
收件人:&nbsp;"xmlyqing00/AFB-URR"<AFB-URR@noreply.github.com&gt;;
抄送:&nbsp;"312358434"<312358434@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xmlyqing00/AFB-URR] A difference between your paper and code. (#2)





  
In your paper, you refer to the resolution of backbone output from resnet.layer3, which output stride is 8. But in your code, you don't change original resnet50's stride, leading to a 16 of output stride.
  
LOL. Interesting quesion. Actually, our code uses the ResNet.layer3 as output. You can see line 47 and line 77 in the AFB-URR.py,
         self.res4 = resnet.layer3  # 1/8, 1024   
By the way, is the davis benchmark which you mentioned in your paper davis17 validation or davis17 test-dev ?
 I use the DAVIS17 train-val dataset for training and evaluation. I didn't test on the test-dev dataset.

**Comment by xmlyqing00** [comment]
> In your paper, you refer to the resolution of backbone output from resnet.layer3, in which output stride is 8. But in your code, you don't change original resnet50's stride, leading to a 16 of output stride.

Thank you for pointing out. Our feature map extracted from the encoders is 1/16 of the original image size and has 1024 channels. We state a paper correction in the README.md





> By the way, is the davis benchmark which you mentioned in your paper davis17 validation or davis17 test-dev ?

I use the DAVIS17 train-val dataset for training and evaluation. I didn't test on the test-dev dataset.

**Comment by xmlyqing00** [comment]
> Hi, I have checked "r4"'s shape. Actually, it is indeed downsampled by 16 stride. &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xmlyqing00/AFB-URR" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月8日(星期天) 中午12:09 收件人:&nbsp;"xmlyqing00/AFB-URR"<AFB-URR@noreply.github.com&gt;; 抄送:&nbsp;"312358434"<312358434@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [xmlyqing00/AFB-URR] A difference between your paper and code. (#2) In your paper, you refer to the resolution of backbone output from resnet.layer3, which output stride is 8. But in your code, you don't change original resnet50's stride, leading to a 16 of output stride. LOL. Interesting quesion. Actually, our code uses the ResNet.layer3 as output. You can see line 47 and line 77 in the AFB-URR.py, self.res4 = resnet.layer3 # 1/8, 1024 By the way, is the davis benchmark which you mentioned in your paper davis17 validation or davis17 test-dev ? I use the DAVIS17 train-val dataset for training and evaluation. I didn't test on the test-dev dataset. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes. You are right. The description of the feature map in our paper was wrong.

**Comment by shoutOutYangJie** [comment]
Fine，I noticed that STM also has the same mistake. Despite it, your work is still great. Thank you for opening training code. @xmlyqing00

**Comment by xmlyqing00** [comment]
> Fine，I noticed that STM also has the same mistake. Despite it, your work is still great. Thank you for opening training code. @xmlyqing00

Thank you. Yes, we forked the STM's code including their code annotation. The code annotations mislead our paper writing LOL. I hope the training code could save your time.

**Comment by shoutOutYangJie** [comment]
Hi, Another question, what effectiveness is it?
‘’‘ 
uncertainty = uncertainty.view(bs, -1).norm(p=2, dim=1) / math.sqrt(frame.shape[-2] * frame.shape[-1])
’‘’
in which calculating uncertainty loss. Before calculate ".mean()", you use L2 norm.

**Comment by shoutOutYangJie** [comment]
And, you still write 1/8 stride at your README. LOL.

**Comment by xmlyqing00** [comment]
> And, you still write 1/8 stride at your README. LOL.

Oh LOL. Now the README should be correct.



> Hi, Another question, what effectiveness is it?
> ‘’‘
> uncertainty = uncertainty.view(bs, -1).norm(p=2, dim=1) / math.sqrt(frame.shape[-2] * frame.shape[-1])
> ’‘’
> in which calculating uncertainty loss. Before calculate ".mean()", you use L2 norm.

Very good question LOL. We did that because at first, we designed the uncertainty value from -1 to 1. We used the mean of square (L2-norm) to tackle the negatives. Now the uncertainty value is from 0 to 1. I don't think there is a big difference between "mean" and the "mean of square". I think the L2-norm is unnecessary and using ".mean()" is enough.  LOL
