### ISSUE TITLE
Hi,  question about time of pretain step 

### ISSUE THREAD

**Issue by shoutOutYangJie** [xmlyqing00/AFB-URR#3]
I finished to collect five static image datasets, according to your readme. 
```
11/08 18:02:44 114763 imgs are used for PreTrain. They are from ['COCO', 'ECSSD', 'MSRA10K', 'PASCAL-S', 'PASCALVOC2012'].
pretrain dataset length is  114763
11/08 18:02:44 Load level 0 dataset: 114763 training cases.
11/08 18:02:51 Random seed: 1604829771
```
pretrained dataset has 114763 images, almostly close to "136032" in your paper. But pretrain time is about 12 hours, which is largely far way from "days to week" in your README.  May I make some mistakes?
```
Main Train:   1%|               | 879/114763 [05:07<10:48:59,  2.92it/s, loss=0.38932 (0.64092 0.56776)]
```

**Comment by xmlyqing00** [comment]
12 hours per epoch is correct, faster than my 20 hours/epoch. I used 12 epochs in total for pretraining. It supposed to take 6 days under your environment.

By the way, could you report how many images used in each image datasets? I want to find out why your images  are less than mine. You can check the image folders one by one or pull my latest codes.
```
	COCO: 121269 imgs.
	ECSSD: 1000 imgs.
	MSRA10K: 10000 imgs.
	PASCAL-S: 850 imgs.
	PASCALVOC2012: 2913 imgs.
```
