### ISSUE TITLE
Great Work! A question about testing on YouTube-VOS

### ISSUE THREAD

**Issue by lyn-rgb** [xmlyqing00/AFB-URR#5]
The offical YouTube-VOS dataset contains the valid set and the valid_all_frames, have you use the valid_all_frames or only the valid for the testing?

**Comment by xmlyqing00** [comment]
I used the valid_all_frames image set for evaluation. To be specific, not the sampled images but all the dense frames.

**Comment by lyn-rgb** [comment]
> I used the valid_all_frames image set for evaluation. To be specific, not the sampled images but all the dense frames.

Thanks a lot. Have you tried testing with sampled images ?

**Comment by xmlyqing00** [comment]
Yes. I can't remember the numbers clearly. I remembered the final score drops about 7 to10, compared with valid all frames.
