### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by longmalongma** [xmlyqing00/AFB-URR#6]
Are there any Settings to reduce memory consumption?When I run with a 2080ti, I always report running out of memory.Still think your code doesn't support multiple GPUs?

**Comment by xmlyqing00** [comment]
The out of memory problem depends on which stage you are in. If you are in the training stage, you can set small `--clip-n`. If you are in the testing stage, you can set small `--budget`. You can set small image sizes in both stages as well.

Currently, our code doesn't support multiple GPUs, you can do that my nn.DataParallel.

**Comment by longmalongma** [comment]
> The out of memory problem depends on which stage you are in. If you are in the training stage, you can set small `--clip-n`. If you are in the testing stage, you can set small `--budget`. You can set small image sizes in both stages as well.
> 
> Currently, our code doesn't support multiple GPUs, you can do that my nn.DataParallel.

Ok, thanks for your reply, I got it!
