### ISSUE TITLE
_version_cuda.so: undefined symbol: 

### ISSUE THREAD

**Issue by longmalongma** [xmlyqing00/AFB-URR#7]
Do you know what caused this problem when I was running your code?
OSError: /GPUFS/.conda/envs/tor17/lib/python3.6/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationESs

**Comment by xmlyqing00** [comment]
Hi!

This is the problem related to `torch_scatter` package. You need to download the corresponding version from https://github.com/rusty1s/pytorch_scatter regarding your environment.

**Comment by longmalongma** [comment]
> Hi!
> 
> This is the problem related to `torch_scatter` package. You need to download the corresponding version from https://github.com/rusty1s/pytorch_scatter regarding your environment.

Ok, thanks for your reply, I got it!
