### ISSUE TITLE
about q and p

### ISSUE THREAD

**Issue by longmalongma** [xmlyqing00/AFB-URR#8]
![image](https://user-images.githubusercontent.com/40291722/117524566-85fe9d00-aff0-11eb-9ce4-87a26c94cc88.png)

Hi, thanks for your great work!  What's the difference between p and q here?What do q and p stand for?

**Comment by xmlyqing00** [comment]
Hi, `p` iterates all pixels / patches in the image, where `q` refers to `p`'s neighbor pixels.
