### ISSUE TITLE
About long time video validation 

### ISSUE THREAD

**Issue by Limingxing00** [xmlyqing00/AFB-URR#9]
Hi, 

Thank you for your nice work! I found the long time video dataset [here](https://www.kaggle.com/gvclsu/long-videos).   

Please tell me how to evaluate the results? Because the ```Annotation``` file is not complete.

**Comment by Limingxing00** [comment]
In addition, what labels did you use during inference? How is it evaluated? (Because the label is not complete)

**Comment by xmlyqing00** [comment]
We modified the original DAVIS evaluation codes to evaluate the scores on the long-time video dataset. We only label the main objects in the video.
